// client/vue/src/components/NewMenuModal.vue
<template>
	<modal name="new-menu-modal" @before-open="beforeOpen" height="auto">
		<div class="modal-background"></div>
		<div class="modal-card">
			<header class="modal-card-head">
				<p class="modal-card-title">Add New Menu</p>
				<button class="delete" aria-label="close"></button>
			</header>
			<section class="modal-card-body">
				<!-- Content ... -->
				<form>
					<div class="field">
						<div class="field">
							<label class="label">New Menu Name</label>
							<div class="control">
								<input class="input" v-model="newMenuName" type="text" placeholder="Add Post" required>
							</div>
						</div>
						<div class="field">
							<label class="label">Linked URL</label>
							<div class="control">
								<input class="input" v-model="linkedURL" type="text" placeholder="http://www.example.com">
							</div>
						</div>
						<div class="field">
							<label class="label">Under Menu</label>
							<div class="control">
								<div class="select is-primary">
									<select v-model="underMenuName">
										<option v-for="item in menuOptions">{{item}}</option>
									</select>
								</div>
							</div>
						</div>
						<!-- <div class="field">
							<label class="label">Under Menu</label>
							<div class="control">
								<input class="input" type="text" placeholder="None" required>
							</div>
						</div> -->
					</div>
				</form>
			</section>
			<footer class="modal-card-foot">
				<button class="button is-success" @click="addMenu(newMenuName)">Add Menu</button>
				<button class="button is-info">Menu Manager</button>
				<button class="button" @click="closeMenu();">Cancel</button>
			</footer>
		</div>
	</modal>
</template>
<script type="text/javascript">
module.exports = {
	data(){
		return {
			showModal: false,
			menuOptions: ['None', 'Some'],
			newMenuName: '',
			linkedURL: '',
			underMenuName: 'None'
		}
	},
	mounted() {
		console.log('mounted in NewMenuModal' + this.menus);
	},
	methods: {
		showDialog: function() {
			this.showModal = true;
		},
		closeMenu: function() {
			this.$modal.hide('new-menu-modal');
		},
		beforeOpen(event) {
			console.log(event.params.menus);
			var vm = this;
			vm.newMenuName = '';
			vm.menuOptions = ['None'];
			for(var i=0; i< event.params.menus.length; i++){
				console.log('event.params.menus[i]= ' + event.params.menus[i]);
				vm.menuOptions.push(event.params.menus[i]);
			}
		},
		addMenu: function(newMenu) {
			console.log('new menu in NewMenuModal: ' + newMenu);


			if(this.underMenuName === 'None' || this.linkedURL === '') {
				this.$emit('new-menu-added', newMenu);
			} else {
				this.$emit('new-menu-added',this.underMenuName + '->' + newMenu + ',' + this.linkedURL);
			}
			this.newMenuName = '';
			this.linkedURL = '';
			this.$modal.hide('new-menu-modal');
			// this.menus.push(newMenu);
			// console.log('vm.$data' + this.$data.toString());

		},
		beforeClose(event) {
			var vm = this;
		}
	}
};
</script>
<style scoped>
form {
	width: 30rem;
}
.modal-background {
	z-index: 0;
};
.v--modal-overlay .v--modal-box {
	left: 0;
	height: auto !important;
	width: auto !important;
};
</style>

// client/react/src/components/NewMenuModal.jsx
import React, { Component } from 'react';

import { addMenuToFbase, addPostToFirebase } from '../api/firebase';
import userStore from '../stores/userStore';
import { showAlert, dashedString, formatURL } from './../utils/utils';
import dataStore from '../stores/dataStore';

class NewMenuModal extends Component {
  state = {
    menuName: '',
    linkedURL: '',
    // menuSelect: 'none',
    isLoading: false,
  };

  onClickSave = () => {
    const { menuName, linkedURL } = this.state;

    // matching vue => creating a post for each menu
    const postData = {
      title: menuName,
      content: '',
      pageURL: linkedURL.length > 0 ? formatURL(linkedURL) : `/${dashedString(menuName)}`,
      tags: '',
      author: `${userStore.profileData.first} ${userStore.profileData.last}`,
    };

    if (menuName.length > 0) {
      this.setState({ isLoading: true });
      addPostToFirebase(postData).then(res => {
        this.setState({ isLoading: false });
        if (res.error) {
          showAlert(res.error.message, 'error');
        } else {
          const { data } = res;
          const menuData = {
            name: menuName,
            linkedURL: linkedURL.length > 0 ? formatURL(linkedURL) : data.pageURL,
            postId: data.id,
          };
          this.setState({ isLoading: true });
          addMenuToFbase(menuData).then(res => {
            this.setState({ isLoading: false });
            if (res.error) {
              showAlert(res.error.message, 'error');
            } else {
              dataStore.menus.push(menuData);
              showAlert('Menu added successfully', 'success');
              this.props.onClose();
            }
          });
        }
      });
    }
  };

  handleInputChange = event => {
    const { target } = event;
    const value = target.type === 'checkbox' ? target.checked : target.value;
    const { name } = target;
    this.setState({
      [name]: value,
    });
  };

  render() {
    return (
      <div className="modal-card">
        <header className="modal-card-head">
          <p className="modal-card-title">Add New Menu</p>
          {/* <button
            className="delete"
            aria-label="close"
            onClick={() => {
              this.props.onClose();
            }}
          /> */}
        </header>
        <section className="modal-card-body">
          <form>
            <div className="field">
              <div className="field">
                <label className="label">New Menu Name</label>
                <div className="control">
                  <input
                    className="input"
                    name="menuName"
                    onChange={this.handleInputChange}
                    type="text"
                    placeholder="About Us"
                    required
                  />
                </div>
              </div>
              <div className="field">
                <label className="label">Linked URL</label>
                <div className="control">
                  <input
                    className="input"
                    name="linkedURL"
                    onChange={this.handleInputChange}
                    type="text"
                    placeholder="http(s)://www.example.com"
                  />
                </div>
              </div>
              {/* <div className="field">
                <label className="label">Under Menu</label>
                <div className="control">
                  <div className="select is-primary">
                    <select name="menuSelect" onChange={this.handleInputChange}>
                      <option value="id1">None</option>
                      <option value="id2">one</option>
                    </select>
                  </div>
                </div>
              </div> */}
            </div>
          </form>
        </section>
        <footer className="modal-card-foot" style={{ paddingBottom: '2rem', paddingTop: '2rem' }}>
          <br />
          <button
            className={`button is-success is-small ${this.state.isLoading ? 'is-loading' : ''}`}
            onClick={() => {
              this.onClickSave();
            }}
          >
            Add Menu
          </button>
          <button
            className="button is-small"
            onClick={() => {
              this.props.onClose();
            }}
          >
            Cancel
          </button>
          <br />
        </footer>
      </div>
    );
  }
}

export default NewMenuModal;
